---
- name: "[backup_pvc] Configure PVC"
  k8s_raw:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "bk-{{ pvol_name }}"
        namespace: "{{ namespace }}"
        labels:
          svc_instance: "{{ _apb_service_instance_id }}"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: "{{ pvol_size }}{{ storage_unit_type }}"
        volumeName: "{{ pvol_name }}"
        storageClassName: "{{ backup_nfs_storageClass }}"

...
