---
- name: "[backup-pvc] Configure PV"
  k8s_raw:
    kubeconfig: '{{ storage_admin_kubeconf }}'
    context: /kubernetes/storage-admin
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ pvol_name }}"
        labels:
          svc_instance: "{{ _apb_service_instance_id }}"
      spec:
        capacity:
          storage: "{{ pvol_size }}{{ storage_unit_type }}"
        accessModes:
          - ReadWriteMany
        nfs:
          path: "{{ backup_storage_nfs_root }}/{{ pvol_name }}"
          server: "{{ backup_storage_nfs_server }}"
        persistentVolumeReclaimPolicy: Retain
        storageClassName: "{{ backup_nfs_storageClass }}"
        claimRef:
          name: "bk-{{ pvol_name }}"
          namespace: "{{ namespace }}"

...
