- kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: ${PV_STORAGE_CLASS}
    labels:
      app: ${APP_LABEL}
  provisioner: no-provisioning
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
