---
- name: Remove exports entry
  file:
    path: /etc/exports.d/{{ pvol_name }}.exports
    follow: no
    state: absent

- name: Check exportfs for pvol_name
  shell: "/sbin/exportfs -s | grep {{ pvol_name }}"
  changed_when: false
  ignore_errors: true
  register: _pvol_in_exportfs

- name: Remove pvol_name from exportfs
  shell: "/sbin/exportfs -u *:{{ backup_storage_nfs_root }}/{{ pvol_name }}"
  when: _pvol_in_exportfs.rc == 0
  register: _exportfs_unshare

- name: unmount volume
  mount:
    path: "{{ backup_storage_nfs_root }}/{{ pvol_name }}"
    src: "/dev/{{ lvm_thinpool.volume_group }}/{{ pvol_name }}"
    state: absent
  register: _mount_volume

- name: remove thin-lv from pool
  lvol:
    vg: "{{ lvm_thinpool.volume_group }}"
    lv: "{{ pvol_name }}"
    force: yes
    state: absent

...
