---
- name: Test local lookups
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    namespace: "jeff-test-apbs"
#    _apb_service_instance_id: "9fa52d3e-c6bb-11e8-9ccf-0a580a80000a"
#    _apb_service_instance_id: "132c7914-c7f9-11e8-9ccf-0a580a80000aj"
    _apb_service_instance_id: "d61a4f56-c8ee-11e8-9ccf-0a580a80000a"
#  roles:
#  - role: ansible.kubernetes-modules
#    install_python_requirements: no
#  - role: ansibleplaybookbundle.asb-modules
  tasks:
  - name: Create unique storage ID
    set_fact:
      storage_UID: "{{ lookup('password', '/dev/null length=12 chars=ascii_lowercase,digits') }}"
      secret_mnt: "/etc/apb-secrets/apb-bkup-nfs-pv-params"
      mode: provision

  - name: Get Parameter Secret Name for current serviceInstance
    shell: oc -n "{{ namespace }}" get serviceinstance -o json | jq -r '.items[] | select(.spec.externalID == "{{ _apb_service_instance_id }}") | .spec.parametersFrom[] | select(.secretKeyRef.key == "parameters") | .secretKeyRef.name'
    register: _parameterSecretName
    failed_when: _parameterSecretName.stdout == ""
    changed_when: false

  - block:
    - name: get current secret value
      shell: oc -n "{{ namespace }}" get secret "{{ _parameterSecretName.stdout }}" -o json | jq -r '.data.parameters'
      register: _secretParametersBefore
      when: _parameterSecretName is defined
      changed_when: false

    - name: add pvolName to apb parameters secret
      shell: "echo {{ _secretParametersBefore.stdout }} | base64 --decode | jq --compact-output '. + {\"storage_UID\":\"{{ storage_UID }}\"}' | base64"
      register: _secretParametersAfter
      when: _secretParametersBefore is defined
      changed_when: false

    - name: update parametersSecretName
      shell: oc -n "{{ namespace }}" get secret "{{ _parameterSecretName.stdout }}" -o json | jq '.data.parameters = "{{ _secretParametersAfter.stdout }}"' | oc replace -f -
      when: _secretParametersAfter is defined

    - name: output
      debug:
        msg:
          - "Preparation:"
          - "  _apb_service_instance_id: {{ _apb_service_instance_id }}"
          - "  _parameterSecretName: {{ _parameterSecretName.stdout }}"
          - "  _secretParametersBefore: {{ _secretParametersBefore.stdout }}"
          - "  _secretParametersAfter : {{ _secretParametersAfter.stdout }}"
    when: _parameterSecretName.stdout != ""

#- name: Provision PV-PVC
#  hosts: localhost
#  gather_facts: false
#  connection: local
#  vars:
#    state: 'present'
#    mode: 'provision'
#  roles:
#  - role: ansible.kubernetes-modules
#    install_python_requirements: no
#  - role: ansibleplaybookbundle.asb-modules
#  - role: backup_pvc
#    playbook_debug: true

...
